export const MCP_SERVER_PRESETS = Object.freeze([
  Object.freeze({
    id: 'chrome-devtools',
    provider: 'mcp_chrome_devtools',
    label: 'Chrome DevTools',
    publisher: 'Google',
    brandColor: '#1A73E8',
    category: 'work',
    searchTerms: 'chrome chromium browser devtools google mcp debugging automation',
    descriptionKey: 'access.chromeDevtoolsMcpDesc',
    hintKey: 'access.chromeDevtoolsMcpHint',
    official: true,
    name: 'chrome_devtools',
    transport: 'stdio',
    command: 'npx',
    args: Object.freeze(['-y', 'chrome-devtools-mcp@latest']),
    env: Object.freeze({}),
    cwd: '',
    url: '',
    headers: Object.freeze({}),
    enabled: true,
    autoApprove: Object.freeze([]),
  }),
  Object.freeze({
    id: 'filesystem',
    provider: 'mcp_filesystem',
    label: 'Filesystem',
    publisher: 'Model Context Protocol',
    brandColor: '#64748B',
    category: 'productivity',
    searchTerms: 'filesystem files folders local mcp reference server',
    descriptionKey: 'access.filesystemMcpDesc',
    hintKey: 'access.filesystemMcpHint',
    official: true,
    showInAccess: false,
    name: 'filesystem',
    transport: 'stdio',
    command: 'npx',
    args: Object.freeze(['-y', '@modelcontextprotocol/server-filesystem', '.']),
    env: Object.freeze({}),
    cwd: '',
    url: '',
    headers: Object.freeze({}),
    enabled: true,
    autoApprove: Object.freeze([]),
  }),
  Object.freeze({
    id: 'fetch',
    provider: 'mcp_fetch',
    label: 'Fetch (Web)',
    publisher: 'Model Context Protocol',
    brandColor: '#E8590C',
    category: 'work',
    searchTerms: 'fetch web http url scraping crawler mcp',
    descriptionKey: 'access.fetchMcpDesc',
    hintKey: 'access.fetchMcpHint',
    official: true,
    name: 'fetch',
    transport: 'stdio',
    command: 'npx',
    args: Object.freeze(['-y', '@modelcontextprotocol/server-fetch']),
    env: Object.freeze({}),
    cwd: '',
    url: '',
    headers: Object.freeze({}),
    enabled: true,
    autoApprove: Object.freeze([]),
  }),
  Object.freeze({
    id: 'sequential-thinking',
    provider: 'mcp_sequential_thinking',
    label: 'Sequential Thinking',
    publisher: 'Model Context Protocol',
    brandColor: '#7048E8',
    category: 'work',
    searchTerms: 'thinking reasoning chain of thought step by step mcp',
    descriptionKey: 'access.sequentialThinkingMcpDesc',
    hintKey: 'access.sequentialThinkingMcpHint',
    official: true,
    name: 'sequential_thinking',
    transport: 'stdio',
    command: 'npx',
    args: Object.freeze(['-y', '@modelcontextprotocol/server-sequential-thinking']),
    env: Object.freeze({}),
    cwd: '',
    url: '',
    headers: Object.freeze({}),
    enabled: true,
    autoApprove: Object.freeze([]),
  }),
  Object.freeze({
    id: 'memory',
    provider: 'mcp_memory',
    label: 'Memory (Knowledge Graph)',
    publisher: 'Model Context Protocol',
    brandColor: '#1098AD',
    category: 'productivity',
    searchTerms: 'memory knowledge graph entity relations mcp',
    descriptionKey: 'access.memoryMcpDesc',
    hintKey: 'access.memoryMcpHint',
    official: true,
    name: 'memory',
    transport: 'stdio',
    command: 'npx',
    args: Object.freeze(['-y', '@modelcontextprotocol/server-memory']),
    env: Object.freeze({}),
    cwd: '',
    url: '',
    headers: Object.freeze({}),
    enabled: true,
    autoApprove: Object.freeze([]),
  }),
  Object.freeze({
    id: 'playwright',
    provider: 'mcp_playwright',
    label: 'Playwright (Browser Automation)',
    publisher: 'Microsoft',
    brandColor: '#2EAD33',
    category: 'work',
    searchTerms: 'playwright browser automation microsoft mcp',
    descriptionKey: 'access.playwrightMcpDesc',
    hintKey: 'access.playwrightMcpHint',
    official: true,
    name: 'playwright',
    transport: 'stdio',
    command: 'npx',
    args: Object.freeze(['-y', '@playwright/mcp@latest']),
    env: Object.freeze({}),
    cwd: '',
    url: '',
    headers: Object.freeze({}),
    enabled: true,
    autoApprove: Object.freeze([]),
  }),
])

export function getMcpServerPreset(id) {
  return MCP_SERVER_PRESETS.find((item) => item.id === id) || null
}

export function findInstalledMcpPreset(servers, presetId) {
  const preset = getMcpServerPreset(presetId)
  if (!preset) return null
  return (Array.isArray(servers) ? servers : []).find((server) => server.name === preset.name) || null
}

export function createMcpServerFromPreset(id) {
  const preset = getMcpServerPreset(id)
  if (!preset) return null
  return {
    name: preset.name,
    transport: preset.transport,
    command: preset.command,
    args: [...preset.args],
    env: { ...preset.env },
    cwd: preset.cwd,
    url: preset.url,
    headers: { ...preset.headers },
    headersText: JSON.stringify(preset.headers, null, 2),
    enabled: preset.enabled,
    autoApprove: [...preset.autoApprove],
  }
}
