import { Pin, Save, Trash2, Users, X } from 'lucide-react'

export default function MemoryEditor({ activeAgentId, agents, editing, onChange, onClose, onDelete, onSave, saving, t, types }) {
  if (!editing) return <div className="flex h-full items-center justify-center text-sm text-ink-fade">{t('memory.selectHint')}</div>
  const update = (patch) => onChange({ ...editing, ...patch })
  return <div className="mx-auto max-w-[720px] space-y-4 px-8 py-6">
    <div className="flex items-center justify-between"><div className="text-sm font-semibold text-ink">{editing.id ? t('memory.editTitle') : t('memory.newTitle')}</div><button type="button" onClick={onClose} className="text-ink-fade hover:text-ink" title={t('memory.close')}><X className="h-4 w-4" /></button></div>
    <div><label className="mb-1.5 block text-xs text-ink-fade">{t('memory.type')}</label><div className="flex gap-1.5">{types.map((type) => <button key={type.id} type="button" onClick={() => update({ type: type.id })} className={`rounded-md border px-3 py-1 text-xs transition-colors ${editing.type === type.id ? 'border-accent bg-accent text-accent-contrast' : 'border-ink/15 bg-paper-2 text-ink-soft hover:border-accent/50'}`} title={type.hint}>{type.label}</button>)}</div></div>
    <Field label={t('memory.titleLabel')}><input value={editing.title} onChange={(event) => update({ title: event.target.value })} placeholder={t('memory.titlePlaceholder')} className="h-9 w-full rounded-md border border-ink/15 bg-paper-2 px-3 text-sm outline-none focus:border-focus" /></Field>
    <Field label={t('memory.bodyLabel')}><textarea value={editing.body} onChange={(event) => update({ body: event.target.value })} rows={10} placeholder={t('memory.bodyPlaceholder')} className="w-full rounded-md border border-ink/15 bg-paper-2 px-3 py-2 font-mono text-sm outline-none focus:border-focus" /><div className="mt-1 text-[10px] text-ink-fade">{t('memory.linkHint')}</div></Field>
    <label className="flex cursor-pointer items-center gap-2 text-xs text-ink-soft"><input type="checkbox" checked={!!editing.pinned} onChange={(event) => update({ pinned: event.target.checked })} /><Pin className="h-3.5 w-3.5" />{t('memory.pinned')}</label>
    <Field label={<span className="flex items-center gap-1"><Users className="h-3 w-3" />{t('memory.bindAgent')}</span>}><select value={editing.agentId || ''} onChange={(event) => update({ agentId: event.target.value || null })} className="h-8 w-full rounded-md border border-ink/15 bg-paper-2 px-2 text-xs outline-none focus:border-focus"><option value="">{t('memory.globalAgent')}</option>{agents.map((agent) => <option key={agent.id} value={agent.id}>{agent.name}{agent.id === activeAgentId ? t('memory.current') : ''}</option>)}</select><div className="mt-1 text-[10px] text-ink-fade">{t('memory.agentHint')}</div></Field>
    <div className="flex items-center gap-2 pt-2"><button type="button" onClick={onSave} disabled={saving || !editing.title.trim() || !editing.body.trim()} className="flex h-8 items-center gap-1 rounded-md bg-accent px-4 text-xs text-accent-contrast hover:bg-accent/90 disabled:opacity-50"><Save className="h-3.5 w-3.5" />{saving ? t('memory.saving') : t('memory.save')}</button>{editing.id && <button type="button" onClick={() => onDelete(editing.id)} className="flex h-8 items-center gap-1 rounded-md border border-rose-300 px-3 text-xs text-rose-700 hover:bg-rose-50"><Trash2 className="h-3.5 w-3.5" />{t('memory.delete')}</button>}</div>
  </div>
}

function Field({ label, children }) { return <div><label className="mb-1.5 block text-xs text-ink-fade">{label}</label>{children}</div> }
