import { Code, Copy, Download, Eye, FileText, Globe, Maximize2, Minimize2, Presentation, Sparkles, Table2, Code2, X } from 'lucide-react'

function ArtifactIcon({ type }) {
  if (['html', 'html_multi', 'mermaid', 'chart', 'svg'].includes(type)) return <Globe className="w-4 h-4" />
  if (type === 'pptx') return <Presentation className="w-4 h-4" />
  if (type === 'xlsx') return <Table2 className="w-4 h-4" />
  if (type === 'react') return <Code2 className="w-4 h-4" />
  return <FileText className="w-4 h-4" />
}

export function PreviewHeader({ preview, maximized, setMaximized, onClose, t }) {
  return <div className="flex items-center gap-3 px-4 py-3 border-b border-dashed border-ink-fade/40 bg-paper"><div className="w-8 h-8 rounded-md border border-ink-fade/40 bg-paper-2 flex items-center justify-center text-ember shrink-0"><ArtifactIcon type={preview.type}/></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><span className="font-mono text-[10px] uppercase tracking-[0.18em] text-ember">{preview.label}</span><span className="text-[11px] text-ink-fade truncate">{preview.summary}</span></div><div className="font-semibold text-ink text-sm truncate" title={preview.filename}>{preview.filename}</div></div><div className="flex items-center gap-1 shrink-0"><button type="button" onClick={() => setMaximized((value) => !value)} className="chat-preview-maximize-toggle w-8 h-8 rounded-md hover:bg-paper-2 flex items-center justify-center text-ink-fade" title={t(maximized ? 'chatPreview.restore' : 'chatPreview.maximize')}>{maximized ? <Minimize2 className="w-3.5 h-3.5"/> : <Maximize2 className="w-3.5 h-3.5"/>}</button><button type="button" onClick={onClose} aria-label={t('chatPreview.close')} className="w-10 h-10 rounded-md bg-paper/80 hover:bg-ember/10 hover:text-ember flex items-center justify-center text-ink-soft" title={t('chatPreview.close')}><X className="w-4 h-4"/></button></div></div>
}

export function PreviewToolbar({ preview, content, view, setView, exports, t }) {
  return <div className="chat-preview-toolbar flex items-center justify-between gap-2 px-4 py-2 border-b border-ink-fade/20 bg-paper-2"><div className="inline-flex border border-ink-fade/40 rounded-md overflow-hidden text-[11px]"><Tab active={view === 'preview'} onClick={() => setView('preview')} icon={<Eye className="w-3 h-3"/>} label={t('chatPreview.preview')}/><Tab active={view === 'source'} onClick={() => setView('source')} icon={<Code className="w-3 h-3"/>} label={t('chatPreview.source')} bordered/></div><div className="chat-preview-toolbar-actions flex items-center gap-1.5"><button type="button" onClick={() => navigator.clipboard?.writeText(content)} className="h-7 px-2 rounded-md border border-ink-fade/40 text-ink-soft inline-flex items-center gap-1 text-[11px]"><Copy className="w-3 h-3"/>{t('chatPreview.copy')}</button>{preview.type === 'pptx' && <button type="button" onClick={exports.handleEditablePptxDownload} disabled={exports.premiumExporting || exports.downloading} className="h-7 px-2 rounded-md border border-ink-fade/40 text-ink-soft inline-flex items-center gap-1 text-[11px] disabled:opacity-50"><Sparkles className="w-3 h-3"/>{exports.premiumExporting ? t('chatPreview.exporting', { progress: exports.premiumProgress }) : t('chatPreview.editable')}</button>}{preview.type === 'html' && <button type="button" onClick={exports.handleHtmlToPptx} disabled={exports.premiumExporting || exports.downloading} className="h-7 px-2 rounded-md border border-ink-fade/40 text-ink-soft inline-flex items-center gap-1 text-[11px] disabled:opacity-50"><Presentation className="w-3 h-3"/>{exports.premiumExporting ? t('chatPreview.converting', { progress: exports.premiumProgress }) : t('chatPreview.convertPptx')}</button>}<button type="button" onClick={exports.handleDownload} disabled={exports.downloading || exports.premiumExporting} className="h-7 px-2.5 rounded-md bg-ember text-paper inline-flex items-center gap-1 text-[11px] disabled:opacity-50"><Download className="w-3 h-3"/>{exports.downloading ? (exports.premiumProgress ? t('chatPreview.generating', { progress: exports.premiumProgress }) : t('chatPreview.generatingShort')) : t('chatPreview.downloadHd')}</button></div></div>
}

function Tab({ active, onClick, icon, label, bordered }) {
  return <button type="button" onClick={onClick} className={`px-3 py-1 inline-flex items-center gap-1.5 ${bordered ? 'border-l border-ink-fade/40' : ''} ${active ? 'bg-ember text-paper' : 'text-ink-soft hover:bg-paper'}`}>{icon}{label}</button>
}
