import { enhanceHtmlPreviewReadability } from '../../../lib/artifactPreview.js'

function escapeHtml(value) {
  return String(value || '').replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;')
}

export function buildReactSandboxDoc(code, labels) {
  const safe = String(code || '').replace(/<\/script>/gi, '<\\/script>')
  const safeLabels = JSON.stringify(labels).replaceAll('<', '\\u003c')
  return enhanceHtmlPreviewReadability(`<!doctype html><html lang="en"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><title>${escapeHtml(labels.title)}</title><script src="/sandbox/react.umd.js"></script><script src="/sandbox/react-dom.umd.js"></script><script src="/sandbox/babel.standalone.js"></script><script src="/sandbox/tailwind.js"></script><style>html,body,#root{margin:0;padding:0;min-height:100vh;background:#fff;color:#111;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}#__err{position:fixed;top:0;left:0;right:0;background:#FEE2E2;color:#7F1D1D;padding:10px 14px;font-family:monospace;font-size:12px;z-index:99999;display:none;max-height:50vh;overflow:auto}#__loading{position:fixed;inset:0;display:flex;align-items:center;justify-content:center;color:#9CA3AF;font-size:13px}</style></head><body><div id="__err"></div><div id="root"><div id="__loading">${escapeHtml(labels.loading)}</div></div><script id="__usercode" type="text/babel" data-presets="react,env" data-type="module">${safe}</script><script>(function(){var labels=${safeLabels};function showErr(msg){var box=document.getElementById('__err');box.textContent=String(msg);box.style.display='block'}window.addEventListener('error',function(e){showErr(labels.runtimeError+(e.error?.stack||e.message||e))});window.addEventListener('unhandledrejection',function(e){showErr(labels.promiseError+(e.reason?.stack||e.reason||e))});function boot(){try{var src=document.getElementById('__usercode').textContent;var rewritten=src.replace(/export\\s+default\\s+/m,'var __default = ');var compiled=Babel.transform(rewritten,{presets:['react',['env',{modules:false}]]}).code;document.getElementById('__loading')?.remove();var React=window.React,ReactDOM=window.ReactDOM;var useState=React.useState,useEffect=React.useEffect,useRef=React.useRef,useMemo=React.useMemo,useCallback=React.useCallback,useReducer=React.useReducer,useContext=React.useContext,useLayoutEffect=React.useLayoutEffect,Fragment=React.Fragment,createElement=React.createElement;var __default;eval(compiled+'\\n;');if(!__default){showErr(labels.missingDefault);return}ReactDOM.createRoot(document.getElementById('root')).render(React.createElement(__default))}catch(err){showErr(labels.compileFailed+(err?.stack||err))}}if(window.Babel)boot();else{var elapsed=0,timer=setInterval(function(){elapsed+=50;if(window.Babel){clearInterval(timer);boot()}else if(elapsed>8000){clearInterval(timer);showErr(labels.dependencyTimeout)}},50)}})();</script></body></html>`)
}
