import { X } from 'lucide-react'

export default function CronJobEditor({ controller, t }) {
  const { form } = controller
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-ink/35 p-4">
      <form onSubmit={controller.create} className="flex max-h-[90vh] w-full max-w-2xl flex-col gap-4 overflow-y-auto rounded-md border border-ink bg-paper p-5 shadow-xl">
        <div className="flex items-center justify-between"><h2 className="font-display text-xl text-ink">{t('cron.newTitle')}</h2><button type="button" onClick={() => controller.setShowCreate(false)} className="text-ink-fade hover:text-ink"><X className="h-4 w-4" /></button></div>
        <div className="grid grid-cols-2 gap-3"><Field label={t('cron.fieldTitle')}><input value={form.title} onChange={(event) => controller.updateForm({ title: event.target.value })} required className="h-9 rounded-md border border-ink/40 bg-paper px-3 text-sm outline-none focus:border-focus" /></Field><Field label={t('cron.fieldAgent')}><select value={form.agentId} onChange={(event) => controller.updateForm({ agentId: event.target.value })} required={form.kind === 'heartbeat'} className="h-9 rounded-md border border-ink/40 bg-paper px-3 text-sm outline-none focus:border-focus"><option value="">{t('cron.allAgents')}</option>{controller.agents.map((agent) => <option key={agent.id} value={agent.id}>{agent.name}</option>)}</select></Field></div>
        <div className="grid grid-cols-3 gap-3"><Field label={t('cron.kind')}><select value={form.kind} onChange={(event) => controller.updateForm({ kind: event.target.value })} className="h-9 rounded-md border border-ink/40 bg-paper px-3 text-sm outline-none focus:border-focus"><option value="cron">{t('cron.kind_cron')}</option><option value="heartbeat">{t('cron.kind_heartbeat')}</option></select></Field><Field label={t('cron.scheduleType')}><select value={form.scheduleType} onChange={(event) => controller.updateForm({ scheduleType: event.target.value })} disabled={form.kind === 'heartbeat'} className="h-9 rounded-md border border-ink/40 bg-paper px-3 text-sm outline-none focus:border-focus disabled:opacity-60">{['at', 'every', 'cron'].map((item) => <option key={item} value={item}>{item}</option>)}</select></Field><Field label={t('cron.scheduleValue')}><input value={form.scheduleValue} onChange={(event) => controller.updateForm({ scheduleValue: event.target.value })} required className="h-9 rounded-md border border-ink/40 bg-paper px-3 text-sm outline-none focus:border-focus" /></Field></div>
        <Field label={t('cron.execType')}><select value={form.execType} onChange={(event) => controller.updateForm({ execType: event.target.value })} className="h-9 rounded-md border border-ink/40 bg-paper px-3 text-sm outline-none focus:border-focus">{['agent_session', 'direct_notify', 'plugin_action'].map((item) => <option key={item} value={item}>{item}</option>)}</select></Field>
        {form.execType === 'agent_session' && <Field label={t('cron.prompt')}><textarea value={form.prompt} onChange={(event) => controller.updateForm({ prompt: event.target.value })} required rows={5} className="resize-y rounded-md border border-ink/40 bg-paper px-3 py-2 text-sm outline-none focus:border-focus" /></Field>}
        {form.execType === 'direct_notify' && <div className="grid grid-cols-2 gap-3"><Field label={t('cron.notifyTitle')}><input value={form.notifyTitle} onChange={(event) => controller.updateForm({ notifyTitle: event.target.value })} className="h-9 rounded-md border border-ink/40 bg-paper px-3 text-sm outline-none focus:border-focus" /></Field><Field label={t('cron.notifyBody')}><input value={form.notifyBody} onChange={(event) => controller.updateForm({ notifyBody: event.target.value })} className="h-9 rounded-md border border-ink/40 bg-paper px-3 text-sm outline-none focus:border-focus" /></Field></div>}
        {form.execType === 'plugin_action' && <div className="grid grid-cols-2 gap-3"><Field label={t('cron.plugin')}><select value={form.pluginId} onChange={(event) => controller.updateForm({ pluginId: event.target.value })} className="h-9 rounded-md border border-ink/40 bg-paper px-3 text-sm outline-none focus:border-focus"><option value="">{t('cron.pluginNone')}</option>{controller.plugins.map((plugin) => <option key={plugin.id} value={plugin.id}>{plugin.name || plugin.id}</option>)}</select></Field><Field label={t('cron.action')}><input value={form.actionId} onChange={(event) => controller.updateForm({ actionId: event.target.value })} className="h-9 rounded-md border border-ink/40 bg-paper px-3 text-sm outline-none focus:border-focus" /></Field><div className="col-span-2"><Field label={t('cron.params')}><textarea value={form.pluginParams} onChange={(event) => controller.updateForm({ pluginParams: event.target.value })} rows={4} className="w-full resize-y rounded-md border border-ink/40 bg-paper px-3 py-2 font-mono text-sm outline-none focus:border-focus" /></Field></div></div>}
        <Field label={t('cron.grants')} hint={t('cron.grantsHint')}><textarea value={form.grantsJson} onChange={(event) => controller.updateForm({ grantsJson: event.target.value })} rows={5} spellCheck={false} className="resize-y rounded-md border border-ink/40 bg-paper px-3 py-2 font-mono text-sm outline-none focus:border-focus" /></Field>
        <div className="flex justify-end gap-2 pt-2"><button type="button" onClick={() => controller.setShowCreate(false)} className="h-9 rounded-md border border-ink-fade/40 px-4 text-sm text-ink-soft hover:bg-paper-2">{t('common.cancel')}</button><button type="submit" disabled={controller.saving} className="h-9 rounded-md bg-ink px-4 text-sm text-paper hover:bg-ink-soft disabled:opacity-60">{controller.saving ? t('common.saving') : t('common.save')}</button></div>
      </form>
    </div>
  )
}

function Field({ children, hint, label }) {
  return <label className="flex flex-col gap-1"><span className="text-xs text-ink-fade">{label}</span>{children}{hint && <span className="text-xs leading-4 text-ink-fade">{hint}</span>}</label>
}
